string group_name
string tip_frame
geometry_msgs/PoseStamped target_pose
MotionOptions options
---
Status status
sensor_msgs/JointState final_joint_state
geometry_msgs/PoseStamped final_pose
---
float32 progress
sensor_msgs/JointState actual_joint_state
geometry_msgs/PoseStamped actual_pose
